# -*- coding: utf-8 -*-
"""Copy of SantanderDevWeek2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOw35rOoScH_HCb_dKARaiP8z6mu8qEY

# Santander Dev Week 2023 (ETL com Python)

**Contexto:** Você é um cientista de dados no Santander e recebeu a tarefa de envolver seus clientes de maneira mais personalizada. Seu objetivo é usar o poder da IA Generativa para criar mensagens de marketing personalizadas que serão entregues a cada cliente.

**Condições do Problema:**

1. Você recebeu uma planilha simples, em formato CSV ('SDW2023.csv'), com uma lista de IDs de usuário do banco:
  ```
  UserID
  1
  2
  3
  4
  5
  ```
2. Seu trabalho é consumir o endpoint `GET https://sdw-2023-prd.up.railway.app/users/{id}` (API da Santander Dev Week 2023) para obter os dados de cada cliente.
3. Depois de obter os dados dos clientes, você vai usar a API do ChatGPT (OpenAI) para gerar uma mensagem de marketing personalizada para cada cliente. Essa mensagem deve enfatizar a importância dos investimentos.
4. Uma vez que a mensagem para cada cliente esteja pronta, você vai enviar essas informações de volta para a API, atualizando a lista de "news" de cada usuário usando o endpoint `PUT https://sdw-2023-prd.up.railway.app/users/{id}`.
"""

# Utilize sua própria URL se quiser ;)
# Repositório da API: https://github.com/digitalinnovationone/santander-dev-week-2023-api
sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

"""## **E**xtract

Extraia a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente.
"""

import pandas as pd

df = pd.read_csv('leonardo-pereira-SDW2023.csv')
user_ids = df['UserID'].tolist()
print(user_ids)

import requests
import json

def get_user(id):
  response = requests.get(f'{sdw2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))

"""## **T**ransform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

low_balance_tips = ['Organizar suas finanças é essencial para alcançar seus objetivos e ter uma vida financeira saudável.', "Organizar suas finanças é essencial para alcançar seus objetivos financeiros e ter tranquilidade financeira. Comece hoje!", 'Organização financeira é a chave para alcançar seus objetivos financeiros. Mantenha o controle para prosperar! 💰📊 #FinançasSaudáveis']
avarage_balance_tips = ['Investir é a rota para o crescimento financeiro. Não adie mais, comece a investir hoje para um futuro mais próspero! 💹📈', 'Investir é a estrada para o crescimento financeiro. Comece agora e faça seu dinheiro trabalhar para você. 💹📈 #InvestirParaProsperar', 'Investir é o caminho para fazer seu dinheiro trabalhar para você. Não deixe o tempo passar, comece a investir agora! 💰🚀 #InvistaComSabedoria']
high_balance_tips = ['Aproveite nossa promoção especial: use seus pontos do banco para descontos exclusivos em suas compras favoritas! 💳🛍️ #EconomizeComSeusPontos', 'Aproveite nossa promoção especial! Use seus pontos do banco na próxima compra e ganhe descontos exclusivos. 💳✨ #EconomizeComOsPontos', 'Aproveite nossa promoção especial: use seus pontos do banco na próxima compra e economize dinheiro! 💳✨']

for user in users:
  if user['account']['limit'] / user['account']['balance'] > 3:
    for data in high_balance_tips:
      user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": data
  })
  elif ((user['account']['limit'] / user['account']['balance'] < 3) and (user['account']['limit'] / user['account']['balance'] > 2)):
    for data in avarage_balance_tips:
      user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": data
  })
  else:
    for data in low_balance_tips:
      user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": data
  })

"""## **L**oad

Atualize a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

def update_user(user):
  response = requests.put(f"{sdw2023_api_url}/users/{user['id']}", json=user)
  return True if response.status_code == 200 else False

for user in users:
  success = update_user(user)
  print(f"User {user['name']} updated? {success}!")